worker_processes 1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;
events
{
	worker_connections 1024;
}


http
{
	include ../mime.types;

	default_type application/octet-stream;

	server_names_hash_bucket_size 512;
	client_header_buffer_size 32k;
	large_client_header_buffers 4 32k;
	client_max_body_size 100m;

	sendfile on;
	tcp_nopush on;

	keepalive_timeout 1200;

	tcp_nodelay on;

	gzip on;
	gzip_min_length 1k;
	gzip_buffers 4 16k;
	gzip_http_version 1.1;
	gzip_comp_level 2;
	gzip_types text/plain application/javascript application/x-javascript text/javascript text/css application/xml application/json image/jpeg image/gif image/png font/ttf font/otf image/svg+xml application/xml+rss text/x-js;
	gzip_vary on;
	gzip_proxied expired no-cache no-store private auth;
	gzip_disable "MSIE [1-6]\.";

	limit_conn_zone $binary_remote_addr zone=perip:10m;
	limit_conn_zone $server_name zone=perserver:10m;

	server_tokens off;
	access_log off;

	server
	{
		include ../common-settings.conf;

		listen 8006;
		server_name $ohr_server_name;

    absolute_redirect off;
    port_in_redirect off;

		location /engine/
		{
			alias $engine_root_directory;
			autoindex off;
		}

		include ../api-proxy.conf;

		location /
		{
			root $dumi_nocode_root_directory;
			try_files $uri $uri/ /index.html;

			index index.html index.htm;
			proxy_set_header Connection "";
			proxy_http_version 1.1;
			proxy_read_timeout 300;
		}
	}

}
